version: "3.9"
name: race-hub-backend
services:
    race-hub-backend-postgres-14.5:
        image: postgres:14.5
        container_name: race-hub-backend-postgres-14.5
        networks:
            race_hub_backend:
                aliases:
                    - race-hub-backend-postgres-14.5
        environment:
            - TZ=America/Sao_Paulo
            - POSTGRES_USER=race_hub_backend
            - POSTGRES_PASSWORD=race_hub_backend
            - POSTGRES_DB=race_hub_backend
            - PGPORT=5432
        ports:
            - "5432:5432"
    race-hub-backend-migrate:
        container_name: race-hub-backend-migrate
        image: migrate/migrate
        depends_on:
            - race-hub-backend-postgres-14.5
        networks:
            - race_hub_backend
        volumes:
            - ./internal/database/migration:/migration
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 5
                window: 120s
        command:
            [
                "-path",
                "/migration",
                "-database",
                "postgres://race_hub_backend:race_hub_backend@race-hub-backend-postgres-14.5:5432/race_hub_backend?sslmode=disable",
                "up"
            ]
    race-hub-backend-sqlc:
        container_name: race-hub-backend-sqlc
        image: kjconroy/sqlc:1.16.0
        depends_on:
        - race-hub-backend-postgres-14.5
        networks:
        - race_hub_backend
        volumes:
        - ./internal/database:/src
        command: [ "generate", "-f", "/src/sqlc.yaml" ]
    race-hub-backend-mockgen:
        container_name: race-hub-backend-mockgen
        image: golang:1.22
        depends_on:
            - race-hub-backend-sqlc
        networks:
            - race_hub_backend
        volumes:
            - .:/src
        working_dir: /src
        command: >
            sh -c " 
            echo 'Iniciando a instalação do mockgen...' && 
            go install go.uber.org/mock/mockgen@latest && 
            echo 'Mockgen instalado com sucesso.' && 
            echo 'Baixando dependências Go...' && 
            echo 'Gerando mocks...' && 
            cd /src/internal/database/sqlc &&
            mockgen . Querier > /src/internal/database/mock/mock.go && 
            echo 'Mocks gerados com sucesso.'"
networks:
    race_hub_backend: