INSERT INTO "user"
    (email, name, password)
VALUES
    ('admin@racehub.com','Admin','$2a$10$DIvRLcErlPMW2pPYj7qUr.2nNrHXSBd/BL/ky20ludw1CINuWSXU2');

INSERT INTO track (fk_created_by_user_id, fk_updated_by_user_id, name, country)
VALUES
    (1, 1, 'Barcelona', 'Espanha'),
    (1, 1, 'Imola', 'Italia'),
    (1, 1, 'Interlagos', 'Brasil'),
    (1, 1, 'Magny-Cours', 'Franca'),
    (1, 1, 'Melbourne', 'Australia'),
    (1, 1, 'Monaco', 'Monaco'),
    (1, 1, 'Montreal', 'Canada'),
    (1, 1, 'Silverstone', 'Reino Unido'),
    (1, 1, 'Sepang', 'Malasia'),
    (1, 1, 'Spielberg', 'Austria'),
    (1, 1, 'Nurburgring', 'Alemanha'),
    (1, 1, 'Hockenheim', 'Alemanha'),
    (1, 1, 'Hungaroring', 'Hungria'),
    (1, 1, 'Spa-Francorchamps', 'Belgica'),
    (1, 1, 'Monza', 'Italia'),
    (1, 1, 'Indianapolis', 'Estados Unidos'),
    (1, 1, 'Suzuka', 'Japão'),
    (1, 1, 'Enna Pergusa', 'Italia'),
    (1, 1, 'Donington Park', 'Reino Unido'),
    (1, 1, 'Oschersleben', 'Alemanha'),
    (1, 1, 'Jacarepagua', 'Brasil'),
    (1, 1, 'Sakhir', 'Bahrein'),
    (1, 1, 'Cleveland', 'Estados Unidos'),
    (1, 1, 'Sachsenring', 'Alemanha'),
    (1, 1, 'Shanghai', 'China'),
    (1, 1, 'Bathurst', 'Australia'),
    (1, 1, 'Road America', 'Estados Unidos'),
    (1, 1, 'Hermanos Rodriguez', 'Mexico'),
    (1, 1, 'Curitiba', 'Brasil'),
    (1, 1, 'Taruma', 'Brasil'),
    (1, 1, 'Surfers Paradise', 'Australia'),
    (1, 1, 'Mar del Plata', 'Argentina'),
    (1, 1, 'Caruaru', 'Brasil'),
    (1, 1, 'Estoril', 'Portugal'),
    (1, 1, 'Taupo', 'Nova Zelandia'),
    (1, 1, 'Alastaro', 'Finlandia'),
    (1, 1, 'Opatija', 'Croacia'),
    (1, 1, 'Jyllands Ringen', 'Dinamarca'),
    (1, 1, 'Arctic Circle', 'Noruega'),
    (1, 1, 'Mondello Park', 'Irlanda'),
    (1, 1, 'Phoenix', 'Estados Unidos'),
    (1, 1, 'Adelaide', 'Australia'),
    (1, 1, 'Laguna Seca', 'Estados Unidos'),
    (1, 1, 'Eastern Creek', 'Australia'),
    (1, 1, 'Brands Hatch', 'Reino Unido'),
    (1, 1, 'St Petersburg', 'Estados Unidos'),
    (1, 1, 'Long Beach', 'Estados Unidos'),
    (1, 1, 'Brno', 'Republica Tcheca'),
    (1, 1, 'Fuji', 'Japão'),
    (1, 1, 'Sebring', 'Estados Unidos'),
    (1, 1, 'Michigan', 'Estados Unidos'),
    (1, 1, 'Edmonton', 'Canada'),
    (1, 1, 'Norisring', 'Alemanha'),
    (1, 1, 'New Hampshire', 'Estados Unidos'),
    (1, 1, 'Snetterton', 'Reino Unido'),
    (1, 1, 'Jerez', 'Espanha'),
    (1, 1, 'Singapura', 'Singapura'),
    (1, 1, 'Detroit', 'Estados Unidos'),
    (1, 1, 'Valencia', 'Espanha'),
    (1, 1, 'Birmingham', 'Estados Unidos'),
    (1, 1, 'Bristol', 'Estados Unidos'),
    (1, 1, 'Autopolis', 'Japão'),
    (1, 1, 'Marina Bay', 'Singapura'),
    (1, 1, 'Daytona', 'Estados Unidos'),
    (1, 1, 'Talladega', 'Estados Unidos'),
    (1, 1, 'Charlotte', 'Estados Unidos'),
    (1, 1, 'Richmond', 'Estados Unidos'),
    (1, 1, 'Mosport', 'Canada'),
    (1, 1, 'Aida', 'Japão'),
    (1, 1, 'Paul Ricard', 'Franca'),
    (1, 1, 'Zolder', 'Belgica'),
    (1, 1, 'Osterreichring', 'Austria'),
    (1, 1, 'Macau', 'Macau'),
    (1, 1, 'Kyalami', 'Africa do Sul'),
    (1, 1, 'Watkins Glen', 'Estados Unidos'),
    (1, 1, 'Rouen', 'Franca'),
    (1, 1, 'Kemora', 'Finlandia'),
    (1, 1, 'Buenos Aires', 'Argentina'),
    (1, 1, 'Algarve', 'Portugal'),
    (1, 1, 'Puebla', 'Mexico'),
    (1, 1, 'Curvelo', 'Brasil'),
    (1, 1, 'Abu Dhabi', 'Emirados Arabes Unidos'),
    (1, 1, 'Pukekohe', 'Nova Zelandia'),
    (1, 1, 'Yas Marina', 'Emirados Arabes Unidos'),
    (1, 1, 'Suzuka', 'Japão'),
    (1, 1, 'Le Mans', 'Franca'),
    (1, 1, 'Aragon', 'Espanha');
