// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RaceSimHub/race-hub-backend/internal/service/notification (interfaces: Contract)
//
// Generated by this command:
//
//	mockgen -destination=./mock/notification_mock.go -package=mock . Contract
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	sqlc "github.com/RaceSimHub/race-hub-backend/internal/database/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockContract is a mock of Contract interface.
type MockContract struct {
	ctrl     *gomock.Controller
	recorder *MockContractMockRecorder
	isgomock struct{}
}

// MockContractMockRecorder is the mock recorder for MockContract.
type MockContractMockRecorder struct {
	mock *MockContract
}

// NewMockContract creates a new mock instance.
func NewMockContract(ctrl *gomock.Controller) *MockContract {
	mock := &MockContract{ctrl: ctrl}
	mock.recorder = &MockContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContract) EXPECT() *MockContractMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContract) Create(message, firstDriver, secondDriver, thirdDriver string, licensePoints int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", message, firstDriver, secondDriver, thirdDriver, licensePoints)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContractMockRecorder) Create(message, firstDriver, secondDriver, thirdDriver, licensePoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContract)(nil).Create), message, firstDriver, secondDriver, thirdDriver, licensePoints)
}

// Delete mocks base method.
func (m *MockContract) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContractMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContract)(nil).Delete), id)
}

// GetLastMessage mocks base method.
func (m *MockContract) GetLastMessage() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastMessage")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMessage indicates an expected call of GetLastMessage.
func (mr *MockContractMockRecorder) GetLastMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMessage", reflect.TypeOf((*MockContract)(nil).GetLastMessage))
}

// GetList mocks base method.
func (m *MockContract) GetList(offset, limit int) ([]sqlc.SelectListNotificationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", offset, limit)
	ret0, _ := ret[0].([]sqlc.SelectListNotificationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockContractMockRecorder) GetList(offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockContract)(nil).GetList), offset, limit)
}

// Update mocks base method.
func (m *MockContract) Update(id int, message, firstDriver, secondDriver, thirdDriver string, licensePoints int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, message, firstDriver, secondDriver, thirdDriver, licensePoints)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockContractMockRecorder) Update(id, message, firstDriver, secondDriver, thirdDriver, licensePoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContract)(nil).Update), id, message, firstDriver, secondDriver, thirdDriver, licensePoints)
}
