// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type Driver struct {
	ID                int64
	FkCreatedByUserID sql.NullInt64
	FkUpdatedByUserID sql.NullInt64
	Name              string
	RaceName          string
	Email             string
	Phone             string
	CreatedDate       time.Time
	UpdatedDate       sql.NullTime
}

type Notification struct {
	ID                int64
	FkCreatedByUserID sql.NullInt64
	Message           sql.NullString
	FirstDriver       sql.NullString
	SecondDriver      sql.NullString
	ThirdDriver       sql.NullString
	LicensePoints     sql.NullInt32
	CreatedDate       time.Time
}

type Track struct {
	ID                int64
	FkCreatedByUserID sql.NullInt64
	FkUpdatedByUserID sql.NullInt64
	Name              string
	Country           string
	CreatedDate       time.Time
	UpdatedDate       sql.NullTime
}

type User struct {
	ID          int64
	Email       string
	Name        string
	Password    string
	CreatedDate time.Time
}
