// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
)

type Notification struct {
	ID            int64
	Message       sql.NullString
	FirstDriver   sql.NullString
	SecondDriver  sql.NullString
	ThirdDriver   sql.NullString
	LicensePoints sql.NullInt32
	CreatedDate   sql.NullTime
}
