// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type Driver struct {
	ID                int64
	FkCreatedByUserID sql.NullInt64
	FkUpdatedByUserID sql.NullInt64
	Name              string
	License           sql.NullString
	Number            sql.NullInt32
	SecondaryNumber   sql.NullInt32
	Neighborhood      sql.NullString
	State             sql.NullString
	City              sql.NullString
	Cep               sql.NullString
	Address           sql.NullString
	AddressNumber     sql.NullString
	Phone             sql.NullString
	SecondaryPhone    sql.NullString
	Country           sql.NullString
	Email             string
	SecondaryEmail    sql.NullString
	Team              sql.NullString
	IDIracing         sql.NullString
	IDSteam           sql.NullString
	Instagram         sql.NullString
	Facebook          sql.NullString
	Twitch            sql.NullString
	PhotoUrl          sql.NullString
	IratingSportsCar  sql.NullInt32
	IratingOval       sql.NullInt32
	IratingFormulaCar sql.NullInt32
	CreatedDate       time.Time
	UpdatedDate       time.Time
}

type Notification struct {
	ID                int64
	FkCreatedByUserID sql.NullInt64
	Message           sql.NullString
	FirstDriver       sql.NullString
	SecondDriver      sql.NullString
	ThirdDriver       sql.NullString
	LicensePoints     sql.NullInt32
	CreatedDate       time.Time
}

type Track struct {
	ID                int64
	FkCreatedByUserID sql.NullInt64
	FkUpdatedByUserID sql.NullInt64
	Name              string
	Country           string
	CreatedDate       time.Time
	UpdatedDate       sql.NullTime
}

type User struct {
	ID                         int64
	Email                      string
	Name                       string
	Password                   string
	CreatedDate                time.Time
	Status                     string
	EmailVerificationToken     sql.NullString
	EmailVerificationExpiresAt sql.NullTime
	Role                       string
}
