// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteNotification(ctx context.Context, id int64) error
	GetLastNotificationMessage(ctx context.Context) (string, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error)
	SelectListNotifications(ctx context.Context, arg SelectListNotificationsParams) ([]SelectListNotificationsRow, error)
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) error
}

var _ Querier = (*Queries)(nil)
