// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteDriver(ctx context.Context, id int64) error
	DeleteNotification(ctx context.Context, id int64) error
	DeleteTrack(ctx context.Context, id int64) error
	GetDriver(ctx context.Context, dollar_1 int64) (GetDriverRow, error)
	GetDriverLink(ctx context.Context, id int64) (GetDriverLinkRow, error)
	GetLastNotificationMessage(ctx context.Context) (string, error)
	InsertDriver(ctx context.Context, arg InsertDriverParams) (int64, error)
	InsertDriverLink(ctx context.Context, arg InsertDriverLinkParams) (int64, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error)
	InsertTrack(ctx context.Context, arg InsertTrackParams) (int64, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (int64, error)
	SelectCountDriverLinks(ctx context.Context, search string) (int64, error)
	SelectCountListDrivers(ctx context.Context, search string) (int64, error)
	SelectDriverLinkStatusByUserID(ctx context.Context, fkUserID int64) (string, error)
	SelectDriverLinks(ctx context.Context, arg SelectDriverLinksParams) ([]SelectDriverLinksRow, error)
	SelectIDIracingByID(ctx context.Context, dollar_1 int64) (sql.NullString, error)
	SelectListDrivers(ctx context.Context, arg SelectListDriversParams) ([]SelectListDriversRow, error)
	SelectListNotifications(ctx context.Context, arg SelectListNotificationsParams) ([]SelectListNotificationsRow, error)
	SelectListTracks(ctx context.Context, arg SelectListTracksParams) ([]SelectListTracksRow, error)
	SelectListTracksCount(ctx context.Context, search string) (int64, error)
	SelectTrackById(ctx context.Context, dollar_1 int64) (SelectTrackByIdRow, error)
	SelectUserByEmail(ctx context.Context, email string) (SelectUserByEmailRow, error)
	SelectUserByEmailVerificationToken(ctx context.Context, arg SelectUserByEmailVerificationTokenParams) (SelectUserByEmailVerificationTokenRow, error)
	UpdateDriver(ctx context.Context, arg UpdateDriverParams) error
	UpdateIratingsByID(ctx context.Context, arg UpdateIratingsByIDParams) error
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) error
	UpdateTrack(ctx context.Context, arg UpdateTrackParams) error
	UpdateUserEmailVerificationToken(ctx context.Context, arg UpdateUserEmailVerificationTokenParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
